name: PR-Actions

on: pull_request

jobs:
  Linting:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python-version: ['2.7','3.7']
        os: ['ubuntu-latest']

    name: Linting OS ${{ matrix.os }} - Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # Need to update if we support other OS's
      - name: Cache PIP Install
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ matrix.python-version }}-pip-lint-${{ hashFiles('**/setup.py') }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.python-version }}-pip-lint
      - name: Run Linting
        run: |
          pip install black flake8
          make lint
